# Generated by Django 3.0 on 2021-04-26 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Año_ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='kardex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_kardex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dato_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_presupuesto', models.CharField(max_length=4)),
                ('proyecto', models.CharField(max_length=30)),
                ('estado', models.CharField(choices=[('PAGADO', 'PAGADO'), ('DEBE PAGAR', 'DEBE PAGAR'), ('ABONO', 'ABONO')], default='DEBE PAGAR', max_length=30)),
                ('pago_uno', models.CharField(blank=True, max_length=20, null=True)),
                ('pago_dos', models.CharField(blank=True, max_length=20, null=True)),
                ('pago_tres', models.CharField(blank=True, max_length=20, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documentos')),
                ('mes', models.CharField(blank=True, choices=[('ENERO', 'ENERO'), ('FEBRERO', 'FEBRERO'), ('MARZO', 'MARZO'), ('ABRIL', 'ABRIL'), ('MAYO', 'MAYO'), ('JUNIO', 'JUNIO'), ('JULIO', 'JULIO'), ('AGOSTO', 'AGOSTO'), ('SEPTIEMBRE', 'SEPTIEMBRE'), ('OCTUBRE', 'OCTUBRE'), ('NOVIEMBRE', 'NOVIEMBRE'), ('DICIEMBRE', 'DICIEMBRE')], max_length=30, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
                ('honorario', models.CharField(max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('año', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.Año_ingreso')),
                ('nombre_kardex', models.ManyToManyField(to='miapp.kardex', verbose_name='ubicacion kardex')),
            ],
        ),
    ]
