# Generated by Django 3.0 on 2021-06-11 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=100)),
                ('archivo_nuevo', models.FileField(blank=True, null=True, upload_to='archivos/')),
            ],
        ),
        migrations.CreateModel(
            name='Certificados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_certificado', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='complete',
            field=models.CharField(blank=True, choices=[('COMPLETADOS', 'COMPLETADOS'), ('SIN DOCUMENTOS', 'SIN DOCUMENTOS'), ('ALGUNOS DOC', 'ALGUNOS DOC')], max_length=50, null=True, verbose_name='Archivos Completos'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='detalle_estado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='documento_presupuesto',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='DOC.PRESUPUESTO'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_catorce',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='I.N.E'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_cinco',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Avaluo Detallado'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_cuatro',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Poder Simple'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_dies',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Exp.Propiedad'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_doce',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Factibilidad'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_dos',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Fotocopia Carnet'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_nueve',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Conjunto Habitacional'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_ocho',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Utilidad Publica'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_once',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Informe Tecnico'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_quince',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Patente Profecional'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_seis',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Dominio Vigente'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_siete',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Certificado Informe Previo'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_trece',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Solicitud'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_tres',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Comprobante de Agua'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='file_uno',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Escritura'),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='pago_cuatro',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='proyecto_completado',
            field=models.CharField(choices=[('APROBADO', 'APROBADO'), ('NO CONCRETADO', 'NO CONCRETADO'), ('INGRESADO', 'INGRESADO'), ('INGRESADO SAG', 'INGRESADO SAG'), ('INGRESADO DOM', 'INGRESADO DOM'), ('OBSERVADO', 'OBSERVADO'), ('EN PROCESO', 'EN PROCESO')], default='EN PROCESO', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Excel DE PAGO'),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'PAGADO'), ('SIN PAGOS', 'SIN PAGOS'), ('ABONO', 'ABONO')], default='DEBE PAGAR', max_length=30),
        ),
        migrations.RemoveField(
            model_name='dato_cliente',
            name='nombre_kardex',
        ),
        migrations.AddField(
            model_name='dato_cliente',
            name='nombre_kardex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.kardex'),
        ),
        migrations.CreateModel(
            name='Estado_Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_file', models.FileField(blank=True, null=True, upload_to='estado_archivo/')),
                ('nombre_estado', models.CharField(max_length=100)),
                ('nombre', models.ManyToManyField(to='miapp.dato_cliente')),
            ],
        ),
    ]
