# Generated by Django 3.0 on 2021-06-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20210611_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_cliente',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
