# Generated by Django 3.0 on 2021-07-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_dato_cliente_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agenda', models.CharField(max_length=100)),
                ('proyecto_agenda', models.CharField(max_length=100)),
                ('sitio', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(max_length=9)),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
