# Generated by Django 3.0 on 2021-07-31 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20210730_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['-id']},
        ),
    ]
