# Generated by Django 3.0 on 2021-07-31 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20210730_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_cliente',
            name='pago_cuatro',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='pago_dos',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='pago_tres',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='pago_uno',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
