# Generated by Django 3.0 on 2021-07-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_auto_20210730_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dato_cliente',
            options={'ordering': ['-id']},
        ),
    ]
