# Generated by Django 3.0 on 2021-08-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_auto_20210802_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_cliente',
            name='pago_quinto',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='PAGO ING O TOPOGR'),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='detalle',
            field=models.CharField(blank=True, choices=[('ARQUITECTURA', 'ARQUITECTURA'), ('INGENIERIA', 'INGENIERIA'), ('TOPOGRAFIA', 'TOPOGRAFIA'), ('ARQUITEC Y ING', 'ARQUIT Y ING'), ('ING Y TOPOGR', 'ING Y TOPOGR'), ('ARQUITEC Y TOPOGR', 'ARQUITEC Y TOPOGR')], max_length=100, null=True),
        ),
    ]
