# Generated by Django 3.0 on 2021-08-02 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_auto_20210802_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dato_cliente',
            name='total',
        ),
    ]
