# Generated by Django 3.0 on 2021-08-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_remove_dato_cliente_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='telefono',
            field=models.CharField(max_length=9),
        ),
    ]
