# Generated by Django 3.0 on 2021-08-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_auto_20210810_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_cliente',
            name='honorario_dos',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
