# Generated by Django 3.0 on 2021-08-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_dato_cliente_honorario_dos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_cliente',
            name='honorario',
            field=models.CharField(max_length=20, verbose_name='Honorario Arquitectura'),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='honorario_dos',
            field=models.CharField(max_length=20, verbose_name='honario Ing o topografia'),
        ),
    ]
