# Generated by Django 3.0 on 2021-08-11 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_auto_20210810_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dato_cliente',
            name='honorario_dos',
            field=models.CharField(blank=True, default='0', max_length=20, null=True, verbose_name='honario Ing o topografia'),
        ),
    ]
