# Generated by Django 3.0 on 2021-08-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0017_auto_20210810_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='dato_cliente',
            name='pago_seis',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='PAGO INGENIRIA O TOPOGRAFIA 2'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='proyecto_agenda',
            field=models.CharField(max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='detalle_estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Informacion Adicional'),
        ),
        migrations.AlterField(
            model_name='dato_cliente',
            name='pago_quinto',
            field=models.CharField(blank=True, default=0, max_length=100, null=True, verbose_name='PAGO INGENIRIA O TOPOGRAFIA 1'),
        ),
    ]
