# Generated by Django 3.0 on 2021-08-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0018_auto_20210810_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('presupuesto_lote', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='persona_lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('sitio', models.CharField(blank=True, max_length=100, null=True)),
                ('honorario', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_uno', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_dos', models.CharField(blank=True, max_length=100, null=True)),
                ('pago_tres', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PAGADO', 'PAGADO'), ('SIN PAGOS', 'SIN PAGOS'), ('ABONO', 'ABONO')], default='DEBE PAGAR', max_length=30)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
