# Generated by Django 3.0 on 2021-08-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0019_lote_persona_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_lote',
            name='lote',
            field=models.ManyToManyField(blank=True, null=True, to='miapp.lote'),
        ),
    ]
